// Package omdb provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package omdb

const (
	APIKeyQueryParamScopes = "APIKeyQueryParam.Scopes"
)

// Defines values for GetIdParamsPlot.
const (
	GetIdParamsPlotFull  GetIdParamsPlot = "full"
	GetIdParamsPlotShort GetIdParamsPlot = "short"
)

// Defines values for GetIdParamsR.
const (
	GetIdParamsRJson GetIdParamsR = "json"
	GetIdParamsRXml  GetIdParamsR = "xml"
)

// Defines values for TitleSearchParamsType.
const (
	TitleSearchParamsTypeMovie  TitleSearchParamsType = "movie"
	TitleSearchParamsTypeSeries TitleSearchParamsType = "series"
)

// Defines values for TitleSearchParamsR.
const (
	TitleSearchParamsRJson TitleSearchParamsR = "json"
	TitleSearchParamsRXml  TitleSearchParamsR = "xml"
)

// Defines values for GetTitleParamsType.
const (
	GetTitleParamsTypeMovie  GetTitleParamsType = "movie"
	GetTitleParamsTypeSeries GetTitleParamsType = "series"
)

// Defines values for GetTitleParamsPlot.
const (
	GetTitleParamsPlotFull  GetTitleParamsPlot = "full"
	GetTitleParamsPlotShort GetTitleParamsPlot = "short"
)

// Defines values for GetTitleParamsR.
const (
	Json GetTitleParamsR = "json"
	Xml  GetTitleParamsR = "xml"
)

// GetIdParams defines parameters for GetId.
type GetIdParams struct {
	// I A valid IMDb ID (e.g. tt0000001)
	I string `form:"i" json:"i"`

	// Plot Return short or full plot
	Plot *GetIdParamsPlot `form:"plot,omitempty" json:"plot,omitempty"`

	// R The response type to return
	R *GetIdParamsR `form:"r,omitempty" json:"r,omitempty"`

	// Callback JSONP callback name
	Callback *string `form:"callback,omitempty" json:"callback,omitempty"`
}

// GetIdParamsPlot defines parameters for GetId.
type GetIdParamsPlot string

// GetIdParamsR defines parameters for GetId.
type GetIdParamsR string

// TitleSearchParams defines parameters for TitleSearch.
type TitleSearchParams struct {
	// S Title of movie or series
	S string `form:"s" json:"s"`

	// Y Year of release
	Y *int `form:"y,omitempty" json:"y,omitempty"`

	// Type Return movie or series
	Type *TitleSearchParamsType `form:"type,omitempty" json:"type,omitempty"`

	// R The response type to return
	R *TitleSearchParamsR `form:"r,omitempty" json:"r,omitempty"`

	// Page Page number to return
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Callback JSONP callback name
	Callback *string `form:"callback,omitempty" json:"callback,omitempty"`
}

// TitleSearchParamsType defines parameters for TitleSearch.
type TitleSearchParamsType string

// TitleSearchParamsR defines parameters for TitleSearch.
type TitleSearchParamsR string

// GetTitleParams defines parameters for GetTitle.
type GetTitleParams struct {
	// T Title of movie or series
	T string `form:"t" json:"t"`

	// Y Year of release
	Y *int `form:"y,omitempty" json:"y,omitempty"`

	// Type Return movie or series
	Type *GetTitleParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Plot Return short or full plot
	Plot *GetTitleParamsPlot `form:"plot,omitempty" json:"plot,omitempty"`

	// R The response type to return
	R *GetTitleParamsR `form:"r,omitempty" json:"r,omitempty"`

	// Callback JSONP callback name
	Callback *string `form:"callback,omitempty" json:"callback,omitempty"`
}

// GetTitleParamsType defines parameters for GetTitle.
type GetTitleParamsType string

// GetTitleParamsPlot defines parameters for GetTitle.
type GetTitleParamsPlot string

// GetTitleParamsR defines parameters for GetTitle.
type GetTitleParamsR string
